
-- Seed membership tiers
INSERT INTO public.membership_tiers (name, name_zh_tw, name_zh_cn, min_jumps, credit_multiplier, perks, perks_zh_tw, perks_zh_cn, color, icon, display_order) VALUES
('Bronze', '銅級', '铜级', 0, 1.0, 
  ARRAY['Welcome bonus $100 credit', 'Referral program access', 'Member-only promotions'],
  ARRAY['迎新獎賞 $100 積分', '推薦計劃', '會員專屬優惠'],
  ARRAY['迎新奖赏 $100 积分', '推荐计划', '会员专属优惠'],
  '#CD7F32', 'award', 1),
('Silver', '銀級', '银级', 3, 1.5,
  ARRAY['1.5x referral bonus', 'Priority booking', 'Free photo package upgrade', 'Birthday bonus credits'],
  ARRAY['1.5倍推薦獎賞', '優先預約', '免費相片套餐升級', '生日積分獎賞'],
  ARRAY['1.5倍推荐奖赏', '优先预约', '免费相片套餐升级', '生日积分奖赏'],
  '#C0C0C0', 'star', 2),
('Gold', '金級', '金级', 10, 2.0,
  ARRAY['2x referral bonus', 'VIP priority booking', 'Free video package', 'Birthday bonus credits', 'Exclusive event invitations'],
  ARRAY['2倍推薦獎賞', 'VIP 優先預約', '免費影片套餐', '生日積分獎賞', '獨家活動邀請'],
  ARRAY['2倍推荐奖赏', 'VIP 优先预约', '免费影片套餐', '生日积分奖赏', '独家活动邀请'],
  '#FFD700', 'crown', 3),
('VIP', 'VIP 尊享', 'VIP 尊享', 25, 3.0,
  ARRAY['3x referral bonus', 'Guaranteed booking slots', 'All media packages included', 'Birthday bonus credits', 'Exclusive event invitations', 'Personal jump coordinator', 'Annual VIP gift'],
  ARRAY['3倍推薦獎賞', '保證預約名額', '所有媒體套餐', '生日積分獎賞', '獨家活動邀請', '專屬跳傘協調員', '年度VIP禮品'],
  ARRAY['3倍推荐奖赏', '保证预约名额', '所有媒体套餐', '生日积分奖赏', '独家活动邀请', '专属跳伞协调员', '年度VIP礼品'],
  '#8B5CF6', 'gem', 4);

-- Seed blog posts
INSERT INTO public.blog_posts (slug, title, title_zh_tw, title_zh_cn, content, content_zh_tw, content_zh_cn, excerpt, excerpt_zh_tw, excerpt_zh_cn, cover_image, category, tags, is_published, published_at, author_name, display_order) VALUES
('first-time-skydiving-guide', 
  'First Time Skydiving: Everything You Need to Know',
  '第一次跳傘：你需要知道的一切',
  '第一次跳伞：你需要知道的一切',
  E'## What to Expect on Your First Skydive\n\nSkydiving for the first time is one of the most exhilarating experiences you''ll ever have.\n\n### Before the Jump\n\n- **Training**: 15-20 minute ground training session\n- **Equipment Check**: Your instructor fits you with a harness\n- **The Aircraft**: Jump from 13,000-15,000 feet\n\n### During Freefall\n\nFreefall lasts 45-60 seconds at speeds up to 200 km/h.\n\n### The Canopy Ride\n\n5-7 minutes of peaceful canopy flight with breathtaking views.\n\n### Tips for First-Timers\n\n1. **Wear comfortable clothes**\n2. **Eat a light meal**\n3. **Stay hydrated**\n4. **Listen to your instructor**\n5. **Enjoy the moment**',
  E'## 第一次跳傘的期望\n\n第一次跳傘是你人生中最令人興奮的體驗之一。\n\n### 跳傘前\n\n- **培訓**：15-20分鐘的地面培訓\n- **設備檢查**：教練會為你裝配安全帶\n- **飛機**：從13,000-15,000英尺起跳\n\n### 自由落體\n\n自由落體約持續45-60秒，速度可達200公里/小時。\n\n### 傘下飛行\n\n5-7分鐘平靜的傘下飛行，欣賞壯麗景色。\n\n### 新手貼士\n\n1. **穿著舒適的衣物**\n2. **吃一頓輕食**\n3. **保持水分**\n4. **聽從教練指示**\n5. **享受當下**',
  E'## 第一次跳伞的期望\n\n第一次跳伞是你人生中最令人兴奋的体验之一。\n\n### 跳伞前\n\n- **培训**：15-20分钟的地面培训\n- **设备检查**：教练会为你装配安全带\n- **飞机**：从13,000-15,000英尺起跳\n\n### 自由落体\n\n自由落体约持续45-60秒，速度可达200公里/小时。\n\n### 伞下飞行\n\n5-7分钟平静的伞下飞行，欣赏壮丽景色。\n\n### 新手贴士\n\n1. **穿着舒适的衣物**\n2. **吃一顿轻食**\n3. **保持水分**\n4. **听从教练指示**\n5. **享受当下**',
  'Everything you need to know before your first tandem skydive.',
  '第一次雙人跳傘前你需要知道的一切。',
  '第一次双人跳伞前你需要知道的一切。',
  'https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=800',
  'guide', ARRAY['beginners', 'tandem', 'tips'], true, now() - interval '7 days', 'Let''s Skydive HK', 1),

('what-to-wear-skydiving',
  'What to Wear Skydiving: A Complete Guide',
  '跳傘穿什麼：完整指南',
  '跳伞穿什么：完整指南',
  E'## Dressing for Your Skydive\n\n### The Basics\n\n- **Athletic wear or casual clothes**\n- **Closed-toe shoes** — sneakers are perfect\n- **Layers** — it''s cold at altitude\n\n### What NOT to Wear\n\n- ❌ Loose scarves or dangling jewelry\n- ❌ High heels or open-toe shoes\n- ❌ Skirts or dresses\n- ❌ Bulky jackets\n\n### Pro Tips\n\n- Bring a hair tie for long hair\n- Remove piercings that might catch\n- Wear clothes you don''t mind getting dirty',
  E'## 跳傘穿搭指南\n\n### 基本要求\n\n- **運動服或休閒服**\n- **包趾鞋**——運動鞋最佳\n- **多層穿著**——高空很冷\n\n### 不要穿\n\n- ❌ 鬆散的圍巾或懸掛的首飾\n- ❌ 高跟鞋或露趾鞋\n- ❌ 裙子或連衣裙\n- ❌ 厚重的外套\n\n### 專業貼士\n\n- 長髮請帶髮圈\n- 取下可能卡住裝備的穿環飾品\n- 穿不介意弄髒的衣服',
  E'## 跳伞穿搭指南\n\n### 基本要求\n\n- **运动服或休闲服**\n- **包趾鞋**——运动鞋最佳\n- **多层穿着**——高空很冷\n\n### 不要穿\n\n- ❌ 松散的围巾或悬挂的首饰\n- ❌ 高跟鞋或露趾鞋\n- ❌ 裙子或连衣裙\n- ❌ 厚重的外套\n\n### 专业贴士\n\n- 长发请带发圈\n- 取下可能卡住装备的穿环饰品\n- 穿不介意弄脏的衣服',
  'A complete guide on what to wear for your skydive.',
  '跳傘穿什麼的完整指南。',
  '跳伞穿什么的完整指南。',
  'https://images.unsplash.com/photo-1601024445121-e5b839450519?w=800',
  'tips', ARRAY['clothing', 'preparation'], true, now() - interval '5 days', 'Let''s Skydive HK', 2),

('tandem-vs-aff',
  'Tandem vs AFF: Which Course is Right for You?',
  'Tandem vs AFF：哪種課程適合你？',
  'Tandem vs AFF：哪种课程适合你？',
  E'## Choosing Your Skydiving Path\n\n### Tandem Skydiving\n\n**Best for**: First-timers, bucket list experiences\n\n- Jump attached to a certified instructor\n- Minimal training (15-20 minutes)\n- No prior experience needed\n\n### AFF (Accelerated Freefall)\n\n**Best for**: Those who want to become independent skydivers\n\n- Structured course (7-8 levels)\n- Solo jumps with instructor supervision\n- Path to A-License certification\n\n### Our Recommendation\n\nStart with a tandem jump. If you catch the bug, AFF is your next step!',
  E'## 選擇你的跳傘之路\n\n### 雙人跳傘 (Tandem)\n\n**適合**：首次體驗者、人生清單\n\n- 與認證教練綁在一起跳\n- 最少培訓（15-20分鐘）\n- 無需任何經驗\n\n### AFF 加速自由落體課程\n\n**適合**：想成為獨立跳傘員的人\n\n- 結構化課程（7-8個級別）\n- 在教練監督下獨立跳傘\n- 通往A牌照認證之路\n\n### 我們的建議\n\n先來一次雙人跳傘。如果你被迷住了，AFF就是下一步！',
  E'## 选择你的跳伞之路\n\n### 双人跳伞 (Tandem)\n\n**适合**：首次体验者、人生清单\n\n- 与认证教练绑在一起跳\n- 最少培训（15-20分钟）\n- 无需任何经验\n\n### AFF 加速自由落体课程\n\n**适合**：想成为独立跳伞员的人\n\n- 结构化课程（7-8个级别）\n- 在教练监督下独立跳伞\n- 通往A牌照认证之路\n\n### 我们的建议\n\n先来一次双人跳伞。如果你被迷住了，AFF就是下一步！',
  'Compare Tandem and AFF to find the right skydiving path for you.',
  '比較 Tandem 和 AFF，找到最適合你的跳傘之路。',
  '比较 Tandem 和 AFF，找到最适合你的跳伞之路。',
  'https://images.unsplash.com/photo-1520437358207-323b43b50729?w=800',
  'guide', ARRAY['tandem', 'aff', 'courses'], true, now() - interval '3 days', 'Let''s Skydive HK', 3),

('skydiving-safety-faq',
  'Skydiving Safety FAQ: Your Questions Answered',
  '跳傘安全FAQ：解答你的疑問',
  '跳伞安全FAQ：解答你的疑问',
  E'## Common Safety Questions\n\n### Is skydiving safe?\n\nModern skydiving is remarkably safe with advances in equipment and training.\n\n### What if the parachute doesn''t open?\n\nEvery rig has two parachutes plus an AAD auto-deploy device.\n\n### Weight and age requirements?\n\n- **Weight**: Under 100kg for tandem\n- **Age**: Minimum 18 years\n- **Health**: No recent surgeries or heart conditions\n\n### Can I skydive if I''m afraid of heights?\n\nYes! The sensation at 15,000 feet is completely different from a tall building.\n\n### What about bad weather?\n\nWe''ll reschedule at no extra cost. Safety always comes first.',
  E'## 常見安全問題\n\n### 跳傘安全嗎？\n\n現代跳傘非常安全，裝備和培訓標準持續進步。\n\n### 降落傘打不開怎麼辦？\n\n每套裝備有兩個傘加AAD自動啟動裝置。\n\n### 體重和年齡要求？\n\n- **體重**：雙人跳傘100公斤以下\n- **年齡**：最低18歲\n- **健康**：無近期手術或心臟病\n\n### 恐高可以跳傘嗎？\n\n可以！15,000英尺的感覺與站在高樓上完全不同。\n\n### 天氣不好怎麼辦？\n\n我們會免費重新安排。安全永遠第一。',
  E'## 常见安全问题\n\n### 跳伞安全吗？\n\n现代跳伞非常安全，装备和培训标准持续进步。\n\n### 降落伞打不开怎么办？\n\n每套装备有两个伞加AAD自动启动装置。\n\n### 体重和年龄要求？\n\n- **体重**：双人跳伞100公斤以下\n- **年龄**：最低18岁\n- **健康**：无近期手术或心脏病\n\n### 恐高可以跳伞吗？\n\n可以！15,000英尺的感觉与站在高楼上完全不同。\n\n### 天气不好怎么办？\n\n我们会免费重新安排。安全永远第一。',
  'Answers to common skydiving safety questions.',
  '跳傘安全常見問題解答。',
  '跳伞安全常见问题解答。',
  'https://images.unsplash.com/photo-1474623809196-26c1d33457cc?w=800',
  'tips', ARRAY['safety', 'faq'], true, now() - interval '1 day', 'Let''s Skydive HK', 4);
