// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmelqjnxllsqofvkoccd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZWxxam54bGxzcW9mdmtvY2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMDM1MjgsImV4cCI6MjA4NDU3OTUyOH0.Crzs4c7x-fnlrcIdF7U46cuFed7FnB6Kpo6Gje5_Ymo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});